test: set -e and .gitignore update

diff --git a/z3st/cases/verification/thermal/nn_conductivity_slab_2D/Allrun b/z3st/cases/verification/thermal/nn_conductivity_slab_2D/Allrun
--- a/z3st/cases/verification/thermal/nn_conductivity_slab_2D/Allrun
+++ b/z3st/cases/verification/thermal/nn_conductivity_slab_2D/Allrun
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e # the script will exit if any command fails
 cd "${0%/*}" || exit 1
 
 echo "Training the conductivity network..."
